In [4]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from sklearn.ensemble import HistGradientBoostingRegressor
import joblib
import holidays
from sklearn.cluster import KMeans
from lightgbm import LGBMRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN

## load_data

In [5]:
def load_data(folder_path):
    dataframes = []
    for filename in os.listdir(folder_path):
        if filename.endswith('.csv'):
            file_path = os.path.join(folder_path, filename)
            df = pd.read_csv(file_path)
            category = os.path.splitext(filename)[0]
            df['Category'] = category
            dataframes.append(df)
    if dataframes:
        merged_data = pd.concat(dataframes, ignore_index=True)
        merged_data['Date'] = pd.to_datetime(merged_data['Date'])
        merged_data.set_index('Date', inplace=True)
    else:
        print("No CSV files found in the specified folder.")
        return pd.DataFrame()

    return merged_data

In [6]:
def load_data2(base_folder_path):
    dataframes = []
    
    for category in os.listdir(base_folder_path):
        category_path = os.path.join(base_folder_path, category)
        
        if os.path.isdir(category_path):
            for filename in os.listdir(category_path):
                if filename.endswith('.csv'):
                    file_path = os.path.join(category_path, filename)
                    df = pd.read_csv(file_path)
                    df['Category'] = category
                    province = os.path.splitext(filename)[0]
                    df['Province'] = province
                    price_columns = df.columns.difference(['Date', 'Category', 'Province'])
                    if not price_columns.empty:
                        df['Price'] = df[price_columns[0]]
                    else:
                        print(f"No price column found in {filename}. Skipping this file.")
                        continue
                    
                    dataframes.append(df)
    
    if dataframes:
        merged_data = pd.concat(dataframes, ignore_index=True)
        merged_data['Date'] = pd.to_datetime(merged_data['Date'])
    else:
        print("No CSV files found in the specified folder.")
        return pd.DataFrame()
    merged_data2 = merged_data.pivot_table(index=['Date', 'Category'], columns='Province', values='Price', aggfunc='first')

    merged_data2.reset_index(inplace=True)
    merged_data2['Category'] = merged_data2['Category'].replace({
    'bawang merah': 'Bawang Merah',
    'bawang putih': 'Bawang Putih Bonggol',
    'cabai merah': 'Cabai Merah Keriting',
    'cabai rawit': 'Cabai Rawit Merah',
    'daging ayam': 'Daging Ayam Ras',
    'daging sapi': 'Daging Sapi Murni',
    'gula': 'Gula Konsumsi',
    'telur ayam': 'Telur Ayam Ras',
    'tepung terigu': 'Tepung Terigu (Curah)',
})
    return merged_data2

In [7]:
def google_trend(folder_path):
    dataframes = []
    for filename in os.listdir(folder_path):
        if filename.endswith('.csv'):
            file_path = os.path.join(folder_path, filename)
            df = pd.read_csv(file_path)
            df['Date'] = pd.to_datetime(df['Date'])
            df['Category'] = filename[:-4]
            df.rename(columns={'Riau Islands': 'Kepulauan Riau', 'Bangka Belitung Islands' : 'Kepulauan Bangka Belitung',
                               'Sumatra Barat' : 'Sumatera Barat', 'Sumatra Utara' : 'Sumatera Utara',
                               'Sumatra Selatan' : 'Sumatera Selatan'}, inplace=True)
            dataframes.append(df)

    if dataframes:
        merged_df = pd.concat(dataframes, ignore_index=True)
        merged_df['Category'] = merged_df['Category'].replace({
    'bawang merah': 'Bawang Merah',
    'bawang putih': 'Bawang Putih Bonggol',
    'cabai merah': 'Cabai Merah Keriting',
    'cabai rawit': 'Cabai Rawit Merah',
    'daging ayam': 'Daging Ayam Ras',
    'daging sapi': 'Daging Sapi Murni',
    'gula': 'Gula Konsumsi',
    'telur ayam': 'Telur Ayam Ras',
    'tepung terigu': 'Tepung Terigu (Curah)',
})
        return merged_df
    else:
        print("No CSV files found in the specified folder.")
        return None

## fillna

In [8]:
def fillna(df):
    missing_percentage = df.isnull().sum() / len(df) * 100
    for column in df.columns:
        if column == 'Price':
                df[column].dropna(inplace=True)
        else:
            df[column] = df[column].fillna(method='ffill')

    return df

## melt

In [9]:
def melt(df, value_name):
    df_reset = df.reset_index()
    melted = df_reset.melt(id_vars=['Date', 'Category'], var_name='Province', value_name=value_name)
    melted.set_index('Date', inplace=True)
    
    return melted

## get_date

In [10]:
def get_date(df, lag, target):
    df['Day'] = df.index.day
    df['day_of_week'] = df.index.dayofweek
    df['Day_of_Year'] = df.index.dayofyear
    df['Month'] = df.index.month
    for i in range(1, lag + 1):
        df[f'lag_{i}'] = df.groupby('Category')[target].shift(i)
    
    periods = [7, 30, 90, 365]
    for period in periods:
        df[f'sin ({period})'] = np.sin(2 * np.pi * df.index.dayofyear / period)
        df[f'cos ({period})'] = np.cos(2 * np.pi * df.index.dayofyear / period)
    
    df.fillna(method='bfill', inplace=True)

    return df

## load_support

In [11]:
def load_support(path, target, is_trend=False):
    df = pd.read_csv(path)
    df.rename(columns={'Unnamed: 0': 'Date'}, inplace=True)
    df.set_index('Date', inplace=True)
    df.index = pd.to_datetime(df.index)
    df = df[[target, 'Category']]
    df_pivoted = df.pivot_table(columns='Category', values=target, index = df.index)
    if is_trend:
        df_pivoted = df_pivoted.reset_index()
        df_pivoted = df_pivoted.melt(id_vars='Date', var_name='Category', value_name=target)    
    return df_pivoted

## train_model

In [12]:
def train_model(df, category):
    model = LGBMRegressor(colsample_bytree = 1.0, learning_rate = 0.4319256222176345,max_depth = 10,
                          min_child_samples = 20,n_estimators = 70, num_leaves = 50, subsample = 0.21727297425491027)
    X = df.drop('Price', axis=1)
    y = df['Price']
    model.fit(X, y)
    y_pred = model.predict(X)
    mape = np.mean(np.abs((y - y_pred) / y)) * 100
    print(f"Mean Absolute Percentage Error for {category}: {mape}")
    model_path = fr'C:\Users\farel\OneDrive\Documents\GitHub\Arkavidia-9\saved_models\{category}.joblib'
    joblib.dump(model, model_path)
    
    return model

## predict

In [13]:
def predict(model, df, train, category):
    model_path = fr'C:\Users\farel\OneDrive\Documents\GitHub\Arkavidia-9\saved_models\{category}.joblib'
    model = joblib.load(model_path)

    df_forecast = df.copy()
    df_forecast['Day'] = df_forecast['Date'].dt.day
    df_forecast['day_of_week'] = df_forecast['Date'].dt.dayofweek
    periods = [7, 30, 365]
    for period in periods:
        df_forecast[f'sin ({period})'] = np.sin(2 * np.pi * df_forecast['Date'].dt.dayofyear / period)
        df_forecast[f'cos ({period})'] = np.cos(2 * np.pi * df_forecast['Date'].dt.dayofyear / period)

    provinces = df_forecast['Province'].unique()
    for province in provinces:
        train_province = train[train['Province'] == province]
        df_province = df_forecast[df_forecast['Province'] == province]
        for j in range(1, 4):
            df_forecast.loc[df_province.index, f'lag_{j}'] = train_province['Price'].iloc[-j] if len(train_province) >= j else None

    predictions = []
    for i in range(len(df_forecast)):
        X_new_row = df_forecast.iloc[i].drop(['Price']).to_frame().T
        y_forecast = model.predict(X_new_row)
        predictions.append(y_forecast[0])
        

        if i < len(df_forecast) - 1:
            province = df_forecast.iloc[i]['Province']
            df_forecast.at[df_forecast.index[i + 1], 'lag_1'] = y_forecast[0]
            for j in range(2, 4):
                df_forecast.at[df_forecast.index[i + 1], f'lag_{j}'] = df_forecast.at[df_forecast.index[i], f'lag_{j-1}']

    df_forecast['Price'] = predictions
    return df_forecast

## tanam

In [14]:
def tanam_bamer(date):
    if date.month in [1, 2]:
        return 1
    else:
        return 0

def tanam_baput(date):
    if date.month in [9, 10, 11]:
        return 1
    else:
        return 0

def tanam_camer(date):
    if date.month in [3, 4, 5, 6, 7, 8]:
        return 1
    else:
        return 0

def tanam_caraw(date):
    if date.month in [3, 4, 5, 6]:
        return 1
    else:
        return 0

## province_cluster

In [15]:
def province_cluster(df):
    province_features = df.groupby('Province').agg({
    'Crude Oil WTI Futures Historical Data': 'mean',
    'Natural Gas Futures Historical Data': 'mean',
    'USDIDR=X': 'mean'
    }).reset_index()
    kmeans = KMeans(n_clusters=3)
    province_features['Province_Cluster'] = kmeans.fit_predict(province_features.drop('Province', axis=1))

    df = df.merge(province_features[['Province', 'Province_Cluster']], on='Province', how='left')
    return df

## commodity_cluster

In [16]:
def commodity_cluster(df):
    commodity_features = df[[
    'Crude Oil WTI Futures Historical Data',
    'Natural Gas Futures Historical Data',
    'Palm Oil Futures Historical Data',
    'US Sugar 11 Futures Historical Data',
    'US Wheat Futures Historical Data'
    ]]
    scaler = StandardScaler()
    commodity_features_scaled = scaler.fit_transform(commodity_features)
    kmeans = KMeans(n_clusters=3)
    df['Commodity_Cluster'] = kmeans.fit_predict(commodity_features_scaled)

    return df

## currency_cluster

In [17]:
def currency_cluster(df):
    currency_features = df[['MYRUSD=X', 'SGDUSD=X', 'THBUSD=X', 'USDIDR=X']]
    scaler = StandardScaler()
    currency_features_scaled = scaler.fit_transform(currency_features)
    kmeans = KMeans(n_clusters=3)
    df['Currency_Cluster'] = kmeans.fit_predict(currency_features_scaled)
    return df

## seasonal_cluster

In [18]:
def seasonal_cluster(df):
    seasonal_features = df[[
    'sin (7)', 'cos (7)', 'sin (30)', 'cos (30)',
    'sin (90)', 'cos (90)', 'sin (365)', 'cos (365)'
    ]]
    scaler = StandardScaler()
    seasonal_features_scaled = scaler.fit_transform(seasonal_features)
    kmeans = KMeans(n_clusters=3)
    df['Seasonal_Cluster'] = kmeans.fit_predict(seasonal_features_scaled)
    return df

## lag_cluster

In [19]:
def lag_cluster(df):
    temp = df.copy()
    lag_features = temp[['lag_1', 'lag_2', 'lag_3', 'lag_4', 'lag_5', 'lag_6', 'lag_7']]
    
# Apply K-Means
    kmeans = KMeans(n_clusters=4)
    df['Lag_Cluster'] = kmeans.fit_predict(lag_features)
    return df

## pipeline

In [20]:
def pipeline(folder_path, support_df1, support_df2, is_train=True):
    df = load_data(folder_path)
    df = melt(df, 'Price')
    df = df.join(support_df1, how='left', rsuffix='_support')
    df = df.join(support_df2, how='left', rsuffix='_support')
    if is_train:
        df = fillna(df)
    df = get_date(df, 7, 'Price')
    df['Category'] = df['Category'].astype('category')
    df['Province'] = df['Province'].astype('category')
    df['tanam_bamer'] = df.index.to_series().apply(tanam_bamer)
    df['tanam_baput'] = df.index.to_series().apply(tanam_baput)
    df['tanam_camer'] = df.index.to_series().apply(tanam_camer)
    df['tanam_caraw'] = df.index.to_series().apply(tanam_caraw)
    support_df2_cols = support_df2.columns
    for col in support_df2_cols:
        df[col] = np.log(df[col])
    df = province_cluster(df)
    df = commodity_cluster(df)
    df = currency_cluster(df)
    df = seasonal_cluster(df)
    df = lag_cluster(df)
    return df

## Training

In [21]:
folder_path = r'C:\Users\farel\OneDrive\Documents\GitHub\Arkavidia-9\Harga Bahan Pangan\train'
uang = load_support(r'C:\Users\farel\OneDrive\Documents\GitHub\Arkavidia-9\forecasted\uang.csv', 'Close')
commodity = load_support(r'C:\Users\farel\OneDrive\Documents\GitHub\Arkavidia-9\forecasted\commodity.csv', 'Price')
train = pipeline(folder_path, uang, commodity)

C:\Users\farel\AppData\Local\Temp\ipykernel_41180\4203322176.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[column] = df[column].fillna(method='ffill')
C:\Users\farel\AppData\Local\Temp\ipykernel_41180\2593147889.py:14: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', inplace=True)
C:\Users\farel\AppData\Local\Temp\ipykernel_41180\1544023134.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  province_features = df.groupby('Province').agg({
C:\Users\farel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:1389: ConvergenceWarning: Number of distinct clusters (2) found smaller than n_clusters (3). Possibly due to duplicate points in X.
  return fit_method(estimator, *args, **kwargs)

In [22]:
categories = train['Category'].unique()
models = {}
for category in categories:
    train_subset = train[train['Category'] == category]
    model = train_model(train_subset, category)
    models[category] = model

all_predictions = []
y_true = []

for category in categories:
    train_subset = train[train['Category'] == category]
    model = models[category]
    X = train_subset.drop('Price', axis=1)
    y_pred = model.predict(X)
    all_predictions.extend(y_pred)
    y_true.extend(train_subset['Price'])


mape_all = np.mean(np.abs((np.array(y_true) - np.array(all_predictions)) / np.array(y_true))) * 100
print(f"Overall Mean Absolute Percentage Error: {mape_all}")

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003576 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6505
[LightGBM] [Info] Number of data points in the train set: 34136, number of used features: 39
[LightGBM] [Info] Start training from score 37476.281638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Mean Absolute Percentage Error for Bawang Merah: 1.3434161895712131
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003094 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6505
[LightGBM] [Info] Number of data points in the train set: 34136, number of used features: 39
[LightGBM] [Info] Start training from score 34920.145887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Mean Absolute Percentage Error for Bawang Putih Bonggol: 0.9401076375652594
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002812 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6502
[LightGBM] [Info] Number of data points in the train set: 34136, number of used features: 38
[LightGBM] [Info] Start training from score 12350.381708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Mean Absolute Percentage Error for Beras Medium: 0.43744586226059934
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004085 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6502
[LightGBM] [Info] Number of data points in the train set: 34136, number of used features: 38
[LightGBM] [Info] Start training from score 14125.894071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Mean Absolute Percentage Error for Beras Premium: 0.37063600816929604
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003205 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6506
[LightGBM] [Info] Number of data points in the train set: 34136, number of used features: 39
[LightGBM] [Info] Start training from score 49859.587825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Mean Absolute Percentage Error for Cabai Merah Keriting: 2.330205182562529
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003556 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6506
[LightGBM] [Info] Number of data points in the train set: 34136, number of used features: 39
[LightGBM] [Info] Start training from score 58017.405378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Mean Absolute Percentage Error for Cabai Rawit Merah: 2.8225854594073856
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003193 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6505
[LightGBM] [Info] Number of data points in the train set: 34136, number of used features: 39
[LightGBM] [Info] Start training from score 37269.169498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Mean Absolute Percentage Error for Daging Ayam Ras: 0.910039561557929
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002666 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6502
[LightGBM] [Info] Number of data points in the train set: 34136, number of used features: 38
[LightGBM] [Info] Start training from score 136399.111202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Mean Absolute Percentage Error for Daging Sapi Murni: 0.4255760690771205
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004141 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6502
[LightGBM] [Info] Number of data points in the train set: 34136, number of used features: 38
[LightGBM] [Info] Start training from score 15704.237169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Mean Absolute Percentage Error for Gula Konsumsi: 0.3496042853502606
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002901 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6420
[LightGBM] [Info] Number of data points in the train set: 34136, number of used features: 39
[LightGBM] [Info] Start training from score 15944.954007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Mean Absolute Percentage Error for Minyak Goreng Curah: 0.7636862040759214
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003034 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6504
[LightGBM] [Info] Number of data points in the train set: 34136, number of used features: 39
[LightGBM] [Info] Start training from score 18877.423541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Mean Absolute Percentage Error for Minyak Goreng Kemasan Sederhana: 0.7466737988916794
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002824 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6504
[LightGBM] [Info] Number of data points in the train set: 34136, number of used features: 39
[LightGBM] [Info] Start training from score 29355.353000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Mean Absolute Percentage Error for Telur Ayam Ras: 0.6967709247387671
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002338 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6502
[LightGBM] [Info] Number of data points in the train set: 34136, number of used features: 38
[LightGBM] [Info] Start training from score 10751.447153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Mean Absolute Percentage Error for Tepung Terigu (Curah): 0.6068815654127082
Overall Mean Absolute Percentage Error: 0.9802791345108209

## Predicting

In [292]:
folder_test = r'C:\Users\farel\OneDrive\Documents\GitHub\Arkavidia-9\Harga Bahan Pangan\test'
test = pipeline(folder_test, uang, commodity)

C:\Users\farel\AppData\Local\Temp\ipykernel_35424\1357967570.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[column] = df[column].fillna(method='ffill')
C:\Users\farel\AppData\Local\Temp\ipykernel_35424\1706092442.py:13: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', inplace=True)

In [327]:
categories = test['Category'].unique()
results = []

for category in categories:
    train_subset = train[train['Category'] == category]
    test_subset = test[test['Category'] == category]
    
    test_subset = test_subset.reset_index()
    
    y_pred = predict(model, test_subset, train_subset, category)
    
    y_pred = y_pred.reset_index(drop=True)
    
    test_subset.loc[:, 'Price'] = y_pred['Price']
    for j in range(1, 4):
        test_subset.loc[:, f'lag_{j}'] = y_pred[f'lag_{j}']
    
    test_subset = test_subset.set_index('Date')
    
    test_subset['id'] = test_subset['Category'].astype(str) + '/' + test_subset['Province'].astype(str) + '/' + (test_subset.index).astype(str)
    
    results.append(test_subset)

prediction = pd.concat(results)

In [333]:
prediction = prediction[['id', 'Price']]
prediction.reset_index()
prediction

                                                    id         Price
0                         Bawang Merah/Aceh/2024-10-01  28766.835651
1                         Bawang Merah/Aceh/2024-10-02  28819.263565
2                         Bawang Merah/Aceh/2024-10-03  29026.078543
3                         Bawang Merah/Aceh/2024-10-04  29110.919229
4                         Bawang Merah/Aceh/2024-10-05  29154.413155
...                                                ...           ...
40659  Tepung Terigu (Curah)/Sumatera Utara/2024-12-27   9757.011332
40660  Tepung Terigu (Curah)/Sumatera Utara/2024-12-28   9744.824073
40661  Tepung Terigu (Curah)/Sumatera Utara/2024-12-29   9639.927659
40662  Tepung Terigu (Curah)/Sumatera Utara/2024-12-30   9594.478062
40663  Tepung Terigu (Curah)/Sumatera Utara/2024-12-31   9485.529928

[40664 rows x 2 columns]

In [334]:
sample_submission = pd.read_csv(r'C:\Users\farel\OneDrive\Documents\GitHub\Arkavidia-9\Harga Bahan Pangan\sample_submission.csv')

In [335]:
submission = prediction.set_index('id').reindex(sample_submission['id']).reset_index()

In [336]:
submission.to_csv('submission12.csv', index=False)

In [141]:
sample_submission

                                                    id  price
0                         Bawang Merah/Aceh/2024-10-01      0
1                         Bawang Merah/Aceh/2024-10-02      0
2                         Bawang Merah/Aceh/2024-10-03      0
3                         Bawang Merah/Aceh/2024-10-04      0
4                         Bawang Merah/Aceh/2024-10-05      0
...                                                ...    ...
40659  Tepung Terigu (Curah)/Sumatera Utara/2024-12-27      0
40660  Tepung Terigu (Curah)/Sumatera Utara/2024-12-28      0
40661  Tepung Terigu (Curah)/Sumatera Utara/2024-12-29      0
40662  Tepung Terigu (Curah)/Sumatera Utara/2024-12-30      0
40663  Tepung Terigu (Curah)/Sumatera Utara/2024-12-31      0

[40664 rows x 2 columns]